package com.io.tatsuki.randomer.Repositories.db;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ITEM".
 */
@Entity
public class Item implements Serializable{

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String category;

    @NotNull
    private String title;

    @NotNull
    private String usetId;

    @NotNull
    private String password;
    private String url;

    @NotNull
    private String imagePath;

    @Generated(hash = 1470900980)
    public Item() {
    }

    public Item(Long id) {
        this.id = id;
    }

    @Generated(hash = 36501850)
    public Item(Long id, @NotNull String category, @NotNull String title, @NotNull String usetId, @NotNull String password,
            String url, @NotNull String imagePath) {
        this.id = id;
        this.category = category;
        this.title = title;
        this.usetId = usetId;
        this.password = password;
        this.url = url;
        this.imagePath = imagePath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(@NotNull String category) {
        this.category = category;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    @NotNull
    public String getUsetId() {
        return usetId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsetId(@NotNull String usetId) {
        this.usetId = usetId;
    }

    @NotNull
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(@NotNull String password) {
        this.password = password;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @NotNull
    public String getImagePath() {
        return imagePath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImagePath(@NotNull String imagePath) {
        this.imagePath = imagePath;
    }

}
